spring:
  application:
    name: NOTIFICATION-SERVICE

server:
  port: 8085


  datasource:
    url: jdbc:postgresql://localhost:5432/notificationdb
    username: postgres
    password: your_password_here
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/