spring:
  application:
    name: RECORD-SERVICE


server:
  port: 8087


  datasource:
    url: jdbc:postgresql://localhost:5432/recorddb
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/