server:
  port: 8081

spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password:

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mysecretkeymysecretkeymysecretkey
  access-expiration: 900000
  refresh-expiration: 604800000


